DROP DATABASE IF EXISTS burger_DB;

CREATE DATABASE burger_DB;

USE burger_DB;

CREATE TABLE burgers(
id NOT NULL AUTO_INCREMENT,
name VARCHAR (50) NOT NULL,
devoured TINYINT(1) DEFAULT '0',
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;